### ISSUE TITLE
親子関係を作ることが出来ない

### ISSUE THREAD

**Issue by oosawatechnica** [ikikko/backlog-template-issue-gas#3]
はじめまして、大沢と申します。
親子関係のチケットを発行しようとしましたが、うまくいかないようです。
サンプルファイルをそのまま使ってテスト的に実行しましたが、チケットは発行されますが、親子関係を作ることが出来ませんでした。
お忙しいところ恐縮ですが、調査ご検討いただければ幸いです。

**Comment by ikikko** [comment]
確かに親子課題を作れないですね。
確認しますので、少々お待ちください。

**Comment by ikikko** [comment]
スクリプトの中身を修正して、親子課題を作れるようにしました。
新たにシートをコピーしていただき、まだ問題あるようでしたら再度報告いただけないでしょうか。

**Comment by oosawatechnica** [comment]
本日、300件ほどのチケットをインポートしまして、問題なく動作いたしました。
本スクリプトがないと、チケット発行がとても大変なので、助かっております。
この度は、ありがとうございました。
