### ISSUE TITLE
Googleの二段階認証を設定しているとエラーが出る

### ISSUE THREAD

**Issue by musus** [ikikko/backlog-template-issue-gas#7]
いつもありがたく使わせていただいています。
二段階認証のオフ時には表示されなかったエラーが二段階認証がオンにされていると表示されます。

```
Error encountered: https://spaceid.backlog.jp/api/v2/issues?apiKey=brabrabarbra&projectId=1073905877&summary=A
PI%E3%83%86%E3%82%B9%E3%83%88 のリクエストに失敗しました（エラー: 400）。サーバー応答の一部: {"errors":[{"message":"error.invalid : issueTypeId","code":7,"moreInfo":"issueTypeId is required."},{"message":"error.invalid : priorityId","code":...（応答の全文を見るには muteHttpExceptions オプションを使用してください）
```

**Comment by ikikko** [comment]
@musus さん

ご報告ありがとうございます。
今こちらで、Google の二段階認証を設定しているアカウントでスプレッドシートをコピーして試したところ、問題なく登録できました。

二段階認証以外は同様の設定（スプレッドシートの内容 / 登録先のスペース・プロジェクト）で行われていても、提示いただいたエラーが出ているということでしょうか？
もし、同様の設定でない場合、設定を合わせた上でどうなるか確認いただいてよろしいでしょうか？

\# 現時点では、Google の二段階認証は、このエラーには関係ないと推測しています。
\# 仕組み的に、Google の認証はあくまでスプレッドシートに対してのもので、Backlog への課題登録は フォームに入力するAPI キーなどのみ関連してくるためです。
